=== xbrles/lenloc-penloc/bin/schemas/lenlocpenloc2010-global.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/identifiers" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.inteco.es/xbrl/lenlocpenloc2010/identifiers" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>
	<xsd:element name="global">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="configReport" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="nsItem" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="prefix" type="xsd:string"/>
									<xsd:attribute name="uri" type="xsd:anyURI"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="unit" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="key" type="xsd:string"/>
									<xsd:attribute name="code" type="xsd:string"/>
									<xsd:attribute name="prefix" type="xsd:string"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="schemaRef">
								<xsd:complexType>
									<xsd:attribute name="uri" type="xsd:anyURI"/>
									<xsd:attribute name="baseUrl" type="xsd:anyURI"/>
									<xsd:attribute name="main" type="xsd:boolean"/>
									<xsd:attribute name="type" type="xsd:string"/>
									<xsd:attribute name="targetNamespace" type="xsd:anyURI"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="configModule" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="definitionRoles" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="role" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="uri" type="xsd:anyURI"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="labelTypeRoles" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="role" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="uri" type="xsd:anyURI"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="file" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:attribute name="uri" type="xsd:anyURI"/>
												<xsd:attribute name="type" type="xsd:string"/>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="presentationRole" type="xsd:string"/>
									<xsd:attribute name="labelRole" type="xsd:string"/>
									<xsd:attribute name="definitionRole" type="xsd:string"/>
									<xsd:attribute name="title" type="xsd:string"/>
									<xsd:attribute name="id" type="xsd:string"/>
									<xsd:attribute name="fileMap" type="xsd:string"/>
									<xsd:attribute name="tuple" type="xsd:boolean" use="optional"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute ref="xml:base"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== xbrles/lenloc-penloc/config/global.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ultima actualización 26/05/2011 13:01h -->
<global xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.inteco.es/xbrl/lenlocpenloc/identifiers" xml:base="taxonomy/" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc/identifiers schemas/lenlocpenloc2010-global.xsd">
	<configReport id="liquidaciones">
		<nsItem prefix="lenloc2" uri="http://www.meh.es/taxonomias/lenloc2"/>
		<nsItem prefix="lenloc2-anexo1" uri="http://www.meh.es/taxonomias/lenloc2-anexo1"/>
		<nsItem prefix="lenloc2-anexo2" uri="http://www.meh.es/taxonomias/lenloc2-anexo2"/>
		<nsItem prefix="lenloc2-anexo3" uri="http://www.meh.es/taxonomias/lenloc2-anexo3"/>
		<nsItem prefix="lenloc2-anexo4" uri="http://www.meh.es/taxonomias/lenloc2-anexo4"/>
		<nsItem prefix="lenloc2-anexo5" uri="http://www.meh.es/taxonomias/lenloc2-anexo5"/>
		<nsItem prefix="lenloc2-econ-gast" uri="http://www.meh.es/taxonomias/lenloc2-econ-gast"/>
		<nsItem prefix="lenloc2-econ-gast-cuentas" uri="http://www.meh.es/taxonomias/lenloc2-econ-gast-cuentas"/>
		<nsItem prefix="lenloc2-econ-gast-abierta" uri="http://www.meh.es/taxonomias/lenloc2-econ-gast-abierta"/>
		<nsItem prefix="lenloc2-econ-gast-importes" uri="http://www.meh.es/taxonomias/lenloc2-econ-gast-importes"/>
		<nsItem prefix="lenloc2-econ-ingr" uri="http://www.meh.es/taxonomias/lenloc2-econ-ingr"/>
		<nsItem prefix="lenloc2-econ-ingr-cuentas" uri="http://www.meh.es/taxonomias/lenloc2-econ-ingr-cuentas"/>
		<nsItem prefix="lenloc2-econ-ingr-abierta" uri="http://www.meh.es/taxonomias/lenloc2-econ-ingr-abierta"/>
		<nsItem prefix="lenloc2-econ-ingr-importes" uri="http://www.meh.es/taxonomias/lenloc2-econ-ingr-importes"/>
		<nsItem prefix="lenloc2-exist" uri="http://www.meh.es/taxonomias/lenloc2-exist"/>
		<nsItem prefix="lenloc2-onp" uri="http://www.meh.es/taxonomias/lenloc2-onp"/>
		<nsItem prefix="lenloc2-onp-deudores-acreedores" uri="http://www.meh.es/taxonomias/lenloc2-onp-deudores-acreedores"/>
		<nsItem prefix="lenloc2-onp-importes" uri="http://www.meh.es/taxonomias/lenloc2-onp-importes"/>
		<nsItem prefix="lenloc2-prog" uri="http://www.meh.es/taxonomias/lenloc2-prog"/>
		<nsItem prefix="lenloc2-prog-cuentas" uri="http://www.meh.es/taxonomias/lenloc2-prog-cuentas"/>
		<nsItem prefix="lenloc2-prog-abierta" uri="http://www.meh.es/taxonomias/lenloc2-prog-abierta"/>
		<nsItem prefix="lenloc2-prog-cuentas-econ-cruzadas" uri="http://www.meh.es/taxonomias/lenloc2-prog-cuentas-econ-cruzadas"/>
		<nsItem prefix="lenloc2-remt" uri="http://www.meh.es/taxonomias/lenloc2-remt"/>
		<nsItem prefix="lenloc2-resultp" uri="http://www.meh.es/taxonomias/lenloc2-resultp"/>
		<nsItem prefix="lenloc2-ref" uri="http://www.meh.es/taxonomias/lenloc2-ref"/>
		<nsItem prefix="iso4217" uri="http://www.xbrl.org/2003/iso4217"/>
		<nsItem prefix="xbrldi" uri="http://xbrl.org/2006/xbrldi"/>
		<unit key="euro" code="EUR" prefix="iso4217"/>
		<unit key="eur" code="EUR" prefix="iso4217"/>
		<unit key="pure" code="pure" prefix="xbrli"/>
		<unit key="shares" code="shares" prefix="xbrli"/>
		<unit key="string" code="string" prefix="xbrli"/>
		<schemaRef uri="lenloc2.xsd" baseUrl="." main="true" type="schema" targetNamespace="http://www.meh.es/taxonomias/lenloc2"/>
		<configModule fileMap="lenloc2010-DI.xml" labelRole="http://www.xbrl.org/2003/role/link" presentationRole="http://www.meh.es/taxonomias/lenloc2/DatosIdentificativos" title="DATOS IDENTIFICATIVOS" id="DI">
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/presentationLinkbaseRef"/>
				<role uri="http://www.xbrl.org/2003/role/labelLinkbaseRef"/>
			</labelTypeRoles>
			<file uri="lenloc2-presentation.xml" type="presentation"/>
			<file uri="lenloc2.xsd" type="schema-root"/>
		</configModule>
		<configModule fileMap="lenloc2010-A1.xml" labelRole="http://www.xbrl.org/2003/role/link" title="IMPORTES DEL ANEXO 1" id="A1">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo1/Anexo1InteresesYRendimientosDevengados"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo1-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo1-definition.xml" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A2.xml" labelRole="http://www.xbrl.org/2003/role/link" title="IMPORTES DEL ANEXO 2" id="A2">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo2/Anexo2OperacionsDeTesoreriaACortoPlazoPresupuestariasYNoPresupuestarias"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo2-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo2-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo2-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo2-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo2-definition.xml" type="dimension"/>
			<file uri="lenloc2-anexo2-definition.xml" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A3P.xml" labelRole="http://www.xbrl.org/2003/role/link" title="IMPORTES DEL ANEXO 3 (intereses pagados)" id="A3P">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo3/Anexo3InteresesPagadosAOtrasAdministracionesPublicas"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo3-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo3-definition.xml" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A3R.xml" labelRole="http://www.xbrl.org/2003/role/link" title="IMPORTES DEL ANEXO 3 (intereses recibidos)" id="A3R">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo3/Anexo3InteresesRecibidosAOtrasAdministracionesPublicas"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo3-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo3.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A4ECP.xml" labelRole="http://www.xbrl.org/2003/role/link" title="EJECUTADOS CON CLASIFICACIÓN PRESUPUESTARIA" id="A4ECP">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo4/Anexo4AvalesEjecutadosClasificacionEconomicaDeGastos"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo4-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo4.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A4ECNP.xml" labelRole="http://www.xbrl.org/2003/role/link" title="EJECUTADOS CON CONCEPTO NO PRESUPUESTARIO" id="A4ECNP">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo4/Anexo4AvalesEjecutadosConceptosNoPresupuestarios"/>
 			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo4-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo4.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A4RCP.xml" labelRole="http://www.xbrl.org/2003/role/link" title="REINTEGRADOS CON CLASIFICACION PRESUPUESTARIA" id="A4RCP">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo4/Anexo4AvalesReintegradosClasificacionEconomicaDeIngresos"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo4-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo4.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A4RCNP.xml" labelRole="http://www.xbrl.org/2003/role/link" title="REINTEGRADOS CON CONCEPTO NO PRESUPUESTARIO" id="A4RCNP">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo4/Anexo4AvalesReintegradosConceptosNoPresupuestarios"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo4-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo4.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-A5.xml" labelRole="http://www.xbrl.org/2003/role/link" title="CONCEPTOS DEL ANEXO 5" id="A5">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-anexo5/Anexo5ObligacionesReconocidasPorLaCCLLAFavorDeUnidadesDelSectorPublicoPorLosDistintosCapitulosPresupuestarios"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
			<file uri="lenloc2-anexo5-definition.xml" type="hypercube"/>
			<file uri="lenloc2-anexo5.xsd" type="dimension"/>
		</configModule>
		<configModule fileMap="lenloc2010-GAST.xml" labelRole="http://www.xbrl.org/2003/role/link" title="IMPORTES DE ECONÓMICA DE GASTOS" id="GAST">
			<definitionRoles>
				<role uri="http://www.meh.es/taxonomias/lenloc2-econ-gast/EconomicaGastos"/>
			</definitionRoles>
			<labelTypeRoles>
				<role uri="http://www.xbrl.org/2003/role/label"/>
			</labelTypeRoles>
