=== xbrles/lenloc-penloc/bin/schemas/lenlocpenloc2010-map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" targetNamespace="http://www.inteco.es/xbrl/lenlocpenloc2010/map" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>El XML Schema para el archivo que contiene las asignaciones de código a XBRL elemento.</xs:documentation>
	</xs:annotation>
	<xs:element name="statement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conceptMap" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="mainSchemaURL" type="xs:anyURI"/>
			<xs:attribute name="mainSchemaPrefix" type="xs:string"/>
			<xs:attribute name="mainSchemaNamespace" type="xs:anyURI"/>
			<xs:attribute name="statementID" type="xs:string">
				<xs:annotation>
					<xs:documentation>Para uso en la creación de nombres de archivo</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="moduleName" type="xs:string"/>
			<xs:attribute name="moduleTitle" type="xs:string"/>
			<xs:attribute name="roleURI" type="xs:anyURI"/>
			<xs:attribute name="roleID" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="conceptMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="member" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="conceptAttributes"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="member">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string"/>
			<xs:attribute name="qname" type="xs:string"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="conceptAttributes">
		<xs:attribute name="outputID" type="xs:string">
			<xs:annotation>
				<xs:documentation>El nombre del tema XBRL</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="inputID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>El codigo Español.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ns" type="xs:anyURI" use="required"/>
		<xs:attribute name="nsPrefix" type="xs:string" use="required"/>
		<xs:attribute name="domain" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Nombre de la dimensión</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="containerDimensionType" type="containerDimensionTypeType" use="optional">
			<xs:annotation>
				<xs:documentation>Tipo de contenedor para los miembros de la dimension en el contexto, segment o scenario</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isTypedDimension" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>Especifica si el tipo de dimension es typed. Si no aparece, la dimensión es explícita</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="parent" type="xs:string" use="optional"/>
		<xs:attribute name="order" type="xs:decimal" use="optional"/>
		<xs:attribute name="abstract" type="xs:boolean" use="optional"/>
	</xs:attributeGroup>
	<xs:simpleType name="containerDimensionTypeType" id="containerDimensionTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="segment"/>
			<xs:enumeration value="scenario"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-GASTA.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-econ-gast-abierta" mainSchemaPrefix="lenloc2-econ-gast-abierta" name="lenloc2010-GASTA" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-abierta_CodigoDeCuenta" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-abierta" nsPrefix="lenloc2-econ-gast-abierta" outputID="CodigoDeCuenta">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-abierta_Descripcion" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-abierta" nsPrefix="lenloc2-econ-gast-abierta" outputID="Descripcion">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-importes_CreditosDefinitivosDelEjercicioCorriente" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-importes" nsPrefix="lenloc2-econ-gast-importes" outputID="CreditosDefinitivosDelEjercicioCorriente">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-importes_ObligacionesReconocidasDelEjercicioCorriente" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-importes" nsPrefix="lenloc2-econ-gast-importes" outputID="ObligacionesReconocidasDelEjercicioCorriente">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-importes_PagosRealizadosDelEjercicioCorriente" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-importes" nsPrefix="lenloc2-econ-gast-importes" outputID="PagosRealizadosDelEjercicioCorriente">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-gast-abierta:FilasDimension" isTypedDimension="true"  inputID="lenloc2-econ-gast-importes_PagosLiquidosDeEjerciciosCerrados" ns="http://www.meh.es/taxonomias/lenloc2-econ-gast-importes" nsPrefix="lenloc2-econ-gast-importes" outputID="PagosLiquidosDeEjerciciosCerrados">
        <member id="lenloc2-econ-gast-abierta_FilasTipoDeDimension" qname="lenloc2-econ-gast-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-A5.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-anexo5" mainSchemaPrefix="lenloc2-anexo5" name="lenloc2010-A5" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_EntidadesReceptoras" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="EntidadesReceptoras">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_NIF" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="NIF">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_Capitulo2" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="Capitulo2">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_Capitulo4" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="Capitulo4">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_Capitulo6" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="Capitulo6">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_Capitulo7" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="Capitulo7">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo5:Filasdimension" inputID="lenloc2-anexo5_Capitulo8" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo5" nsPrefix="lenloc2-anexo5" outputID="Capitulo8">
		<member id="lenloc2-anexo5_FilasTipoDeDimension" qname="lenloc2-anexo5:FilasTipoDeDimension"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-DEU.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-onp" mainSchemaPrefix="lenloc2-onp" name="lenloc2010-DEU" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:DeudoresPagosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_DeudoresPagosPendientesAplicacionSaldoRectificaciones" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="DeudoresPagosPendientesAplicacionSaldoRectificaciones">
		<!--Todos los member son dimension-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_DeudoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:DeudoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionPagos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionPagos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:DeudoresPagosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_DeudoresPagosPendientesAplicacionPagosEfectuados" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="DeudoresPagosPendientesAplicacionPagosEfectuados">
		<!--Todos los member son diemnsion-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_DeudoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:DeudoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionPagos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionPagos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:DeudoresPagosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_DeudoresPagosPendientesAplicacionTotalCargo" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="DeudoresPagosPendientesAplicacionTotalCargo">
		<!--Todos los member son dimension-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_DeudoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:DeudoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionPagos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionPagos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc-onp:DeudoresPagosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_DeudoresPagosPendientesAplicacionDataIngreso" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="DeudoresPagosPendientesAplicacionDataIngreso">
		<!--Todos los member son dimension-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_DeudoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:DeudoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionPagos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionPagos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:DeudoresPagosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_DeudoresPagosPendientesAplicacionSaldoPendiente" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="DeudoresPagosPendientesAplicacionSaldoPendiente">
		<!--Todos los member son dimensio-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_DeudoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:DeudoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionPagos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionPagos"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-DI.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2" mainSchemaPrefix="lenloc2" name="lenloc2010-DI" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap abstract="true" inputID="lenloc2_identificacion_empresa" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="identificacion_empresa"/>
	<conceptMap abstract="false" inputID="lenloc2_nombre_empresa" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="nombre_empresa"/>
	<conceptMap abstract="true" inputID="lenloc2_identificacion_ente" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="identificacion_ente"/>
	<conceptMap abstract="false" inputID="lenloc2_cdcorp" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="cdcorp"/>
	<conceptMap abstract="false" inputID="lenloc2_cdprov" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="cdprov"/>
	<conceptMap abstract="false" inputID="lenloc2_tiporg1" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="tiporg1"/>
	<conceptMap abstract="false" inputID="lenloc2_tiporg2" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="tiporg2"/>
	<conceptMap abstract="false" inputID="lenloc2_tiporg3" ns="http://www.meh.es/taxonomias/lenloc2" nsPrefix="lenloc2" outputID="tiporg3"/>
</statement>
