=== xbrles/lenloc-penloc/bin/schemas/lenlocpenloc2010-map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" targetNamespace="http://www.inteco.es/xbrl/lenlocpenloc2010/map" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>El XML Schema para el archivo que contiene las asignaciones de código a XBRL elemento.</xs:documentation>
	</xs:annotation>
	<xs:element name="statement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conceptMap" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="mainSchemaURL" type="xs:anyURI"/>
			<xs:attribute name="mainSchemaPrefix" type="xs:string"/>
			<xs:attribute name="mainSchemaNamespace" type="xs:anyURI"/>
			<xs:attribute name="statementID" type="xs:string">
				<xs:annotation>
					<xs:documentation>Para uso en la creación de nombres de archivo</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="moduleName" type="xs:string"/>
			<xs:attribute name="moduleTitle" type="xs:string"/>
			<xs:attribute name="roleURI" type="xs:anyURI"/>
			<xs:attribute name="roleID" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="conceptMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="member" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="conceptAttributes"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="member">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string"/>
			<xs:attribute name="qname" type="xs:string"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="conceptAttributes">
		<xs:attribute name="outputID" type="xs:string">
			<xs:annotation>
				<xs:documentation>El nombre del tema XBRL</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="inputID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>El codigo Español.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ns" type="xs:anyURI" use="required"/>
		<xs:attribute name="nsPrefix" type="xs:string" use="required"/>
		<xs:attribute name="domain" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Nombre de la dimensión</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="containerDimensionType" type="containerDimensionTypeType" use="optional">
			<xs:annotation>
				<xs:documentation>Tipo de contenedor para los miembros de la dimension en el contexto, segment o scenario</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isTypedDimension" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>Especifica si el tipo de dimension es typed. Si no aparece, la dimensión es explícita</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="parent" type="xs:string" use="optional"/>
		<xs:attribute name="order" type="xs:decimal" use="optional"/>
		<xs:attribute name="abstract" type="xs:boolean" use="optional"/>
	</xs:attributeGroup>
	<xs:simpleType name="containerDimensionTypeType" id="containerDimensionTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="segment"/>
			<xs:enumeration value="scenario"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-RT.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-remt" mainSchemaPrefix="lenloc2-remt" name="lenloc2010-RT" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-remt:FilasdeRemanentedeTesoreriadimension" inputID="lenloc2-remt_ImporteEjercicioActual" ns="http://www.meh.es/taxonomias/lenloc2-remt" nsPrefix="lenloc2-remt" outputID="ImporteEjercicioActual">
		<!--El primer member es un dimension-domain y no un domain-member como el resto. Hay que averiguar si se reporta o no-->
		<member id="R79t" qname="lenloc2-remt:RemanenteDeTesoreriaParaGastosGeneralesAjustado"/>
		<member id="R69t" qname="lenloc2-remt:SaldoDeObligacionesPorDevolucionDeIngresosPendientesDeAplicarAlPresupuestoA31DeDiciembre"/>
		<member id="R59t" qname="lenloc2-remt:SaldoDeObligacionesPendientesDeAplicarAlPresupuestoA31DeDiciembre"/>
		<member id="R49t" qname="lenloc2-remt:RemanenteDeTesoreriaParaGastosGenerales"/>
		<member id="R39t" qname="lenloc2-remt:RemanenteDeTesoreria"/>
		<member id="R29t" qname="lenloc2-remt:FondosLiquidos"/>
		<member id="R09t" qname="lenloc2-remt:TotalDerechosPendientesDeCobro"/>
		<member id="R01" qname="lenloc2-remt:DerechosPendientesDeCobro_DelPresupuestoCorriente"/>
		<member id="R02" qname="lenloc2-remt:DerechosPendientesDeCobro_DePresupuestosCerrados"/>
		<member id="R04" qname="lenloc2-remt:DerechosPendientesDeCobro_DeOtrasOperacionesNoPresupuestarias"/>
		<member id="R06" qname="lenloc2-remt:DerechosPendientesDeCobro_CobrosRealizadosPendientesDeAplicacionDefinitiva"/>
		<member id="R19" qname="lenloc2-remt:TotalObligacionesPendientesDePago"/>
		<member id="R11" qname="lenloc2-remt:ObligacionesPendientesDePago_DelPresupuestoCorriente"/>
		<member id="R12" qname="lenloc2-remt:ObligacionesPendientesDePago_DelPresupuestoCerrados"/>
		<member id="R15" qname="lenloc2-remt:ObligacionesPendientesDePago_DeOperacionesNoPresupuestarias"/>
		<member id="R16" qname="lenloc2-remt:ObligacionesPendientesDePago_PagosRealizadosPendientesDeAplicacionDefinitiva"/>
		<member id="R41" qname="lenloc2-remt:SaldosDeDudosoCobro"/>
		<member id="R42" qname="lenloc2-remt:ExcesoDeFinanciacionAfectada"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-A3R.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-anexo3" mainSchemaPrefix="lenloc2-anexo3" name="lenloc2010-A3R" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo3:Cuentasinteresesrecibidosdimension" inputID="lenloc2-anexo3_DerechosReconocidosNetos" ns="http://www.meh.es/taxonomias/lenloc2-anexo3" nsPrefix="lenloc2-anexo3" outputID="DerechosReconocidosNetos">
		<!--El primer member es un dimension-domain y no un domain-member-->
		<member id="lenloc2-anexo3_InteresesRecibidosdevengadosDeOtrasAdministracionesPublicas" qname="lenloc2-anexo3:InteresesRecibidosdevengadosDeOtrasAdministracionesPublicas"/>
		<member id="lenloc2-anexo3_DelEstadoYSusOrganismos" qname="lenloc2-anexo3:DelEstadoYSusOrganismos"/>
		<member id="lenloc2-anexo3_DeLaSeguridadSocial" qname="lenloc2-anexo3:DeLaSeguridadSocial"/>
		<member id="lenloc2-anexo3_DeLasComunidadesAutonomas" qname="lenloc2-anexo3:DeLasComunidadesAutonomas"/>
		<member id="lenloc2-anexo3_DeOtrasCorporacionesLocales" qname="lenloc2-anexo3:DeOtrasCorporacionesLocales"/>
		<member id="lenloc2-anexo3_InteresesDevengados_Resto" qname="lenloc2-anexo3:InteresesDevengados_Resto"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo3:Cuentasinteresesrecibidosdimension" inputID="lenloc2-anexo3_InteresesDevengados_InteresesDevengados" ns="http://www.meh.es/taxonomias/lenloc2-anexo3" nsPrefix="lenloc2-anexo3" outputID="InteresesDevengados_InteresesDevengados">
		<member id="lenloc2-anexo3_InteresesRecibidosdevengadosDeOtrasAdministracionesPublicas" qname="lenloc2-anexo3:InteresesRecibidosdevengadosDeOtrasAdministracionesPublicas"/>
		<member id="lenloc2-anexo3_DelEstadoYSusOrganismos" qname="lenloc2-anexo3:DelEstadoYSusOrganismos"/>
		<member id="lenloc2-anexo3_DeLaSeguridadSocial" qname="lenloc2-anexo3:DeLaSeguridadSocial"/>
		<member id="lenloc2-anexo3_DeLasComunidadesAutonomas" qname="lenloc2-anexo3:DeLasComunidadesAutonomas"/>
		<member id="lenloc2-anexo3_DeOtrasCorporacionesLocales" qname="lenloc2-anexo3:DeOtrasCorporacionesLocales"/>
		<member id="lenloc2-anexo3_InteresesDevengados_Resto" qname="lenloc2-anexo3:InteresesDevengados_Resto"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-A3P.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-anexo3" mainSchemaPrefix="lenloc2-anexo3" name="lenloc2010-A3P" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo3:Cuentasinteresespagadosdimension" inputID="lenloc2-anexo3_ObligacionesReconocidasNetas" ns="http://www.meh.es/taxonomias/lenloc2-anexo3" nsPrefix="lenloc2-anexo3" outputID="ObligacionesReconocidasNetas">
		<!--El primer member es un dimension-domain y no un domain_member-->
		<member id="lenloc2-anexo3_InteresesPagadosdevengadosAOtrasAdministracionesPublicas" qname="lenloc2-anexo3:InteresesPagadosdevengadosAOtrasAdministracionesPublicas"/>
		<member id="lenloc2-anexo3_AlEstadoYASusOrganismos" qname="lenloc2-anexo3:AlEstadoYASusOrganismos"/>
		<member id="lenloc2-anexo3_ALaSeguridadSocial" qname="lenloc2-anexo3:ALaSeguridadSocial"/>
		<member id="lenloc2-anexo3_ALasComunidadesAutonomas" qname="lenloc2-anexo3:ALasComunidadesAutonomas"/>
		<member id="lenloc2-anexo3_AOtrasCorporacionesLocales" qname="lenloc2-anexo3:AOtrasCorporacionesLocales"/>
		<member id="lenloc2-anexo3_Resto" qname="lenloc2-anexo3:Resto"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo3:Cuentasinteresespagadosdimension" inputID="lenloc2-anexo3_InteresesPagados_InteresesDevengados" ns="http://www.meh.es/taxonomias/lenloc2-anexo3" nsPrefix="lenloc2-anexo3" outputID="InteresesPagados_InteresesDevengados">
		<member id="lenloc2-anexo3_InteresesPagadosdevengadosAOtrasAdministracionesPublicas" qname="lenloc2-anexo3:InteresesPagadosdevengadosAOtrasAdministracionesPublicas"/>
		<member id="lenloc2-anexo3_AlEstadoYASusOrganismos" qname="lenloc2-anexo3:AlEstadoYASusOrganismos"/>
		<member id="lenloc2-anexo3_ALaSeguridadSocial" qname="lenloc2-anexo3:ALaSeguridadSocial"/>
		<member id="lenloc2-anexo3_ALasComunidadesAutonomas" qname="lenloc2-anexo3:ALasComunidadesAutonomas"/>
		<member id="lenloc2-anexo3_AOtrasCorporacionesLocales" qname="lenloc2-anexo3:AOtrasCorporacionesLocales"/>
		<member id="lenloc2-anexo3_Resto" qname="lenloc2-anexo3:Resto"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-RP.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-resultp" mainSchemaPrefix="lenloc2-resultp" name="lenloc2010-RP" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
    <conceptMap containerDimensionType="segment" domain="lenloc2-resultp:ConceptosdelresultadopresupuestarioDimension" inputID="RP.C1" ns="http://www.meh.es/taxonomias/lenloc2-resultp" nsPrefix="lenloc2-resultp" outputID="DerechosReconocidosNetosC1">
        <member id="RP.A" qname="lenloc2-resultp:AResultadoPresupuestarioDelEjercicioC1-C2"/>
        <member id="RP.1" qname="lenloc2-resultp:TotalOperacionesNoFinancierasAB"/>
        <member id="RP.1.a" qname="lenloc2-resultp:AOperacionesCorrientes"/>
        <member id="RP.1.b" qname="lenloc2-resultp:BOtrasOperacionesNoFinancieras"/>
        <member id="RP.2" qname="lenloc2-resultp:ActivosFinancieros"/>
        <member id="RP.3" qname="lenloc2-resultp:PasivosFinancieros"/>
    </conceptMap>
    <conceptMap containerDimensionType="segment" domain="lenloc2-resultp:ConceptosdelresultadopresupuestarioDimension" inputID="RP.C2" ns="http://www.meh.es/taxonomias/lenloc2-resultp" nsPrefix="lenloc2-resultp" outputID="ObligacionesReconocidasNetasC2">
        <member id="RP.A" qname="lenloc2-resultp:AResultadoPresupuestarioDelEjercicioC1-C2"/>
        <member id="RP.1" qname="lenloc2-resultp:TotalOperacionesNoFinancierasAB"/>
        <member id="RP.1.a" qname="lenloc2-resultp:AOperacionesCorrientes"/>
        <member id="RP.1.b" qname="lenloc2-resultp:BOtrasOperacionesNoFinancieras"/>
        <member id="RP.2" qname="lenloc2-resultp:ActivosFinancieros"/>
        <member id="RP.3" qname="lenloc2-resultp:PasivosFinancieros"/>
    </conceptMap>
    <conceptMap containerDimensionType="segment" domain="lenloc2-resultp:ConceptosdelresultadopresupuestarioDimension" inputID="RP.C3" ns="http://www.meh.es/taxonomias/lenloc2-resultp" nsPrefix="lenloc2-resultp" outputID="ResultadoPresupuestarioC3">
        <member id="RP.A" qname="lenloc2-resultp:AResultadoPresupuestarioDelEjercicioC1-C2"/>
        <member id="RP.1" qname="lenloc2-resultp:TotalOperacionesNoFinancierasAB"/>
        <member id="RP.1.a" qname="lenloc2-resultp:AOperacionesCorrientes"/>
        <member id="RP.1.b" qname="lenloc2-resultp:BOtrasOperacionesNoFinancieras"/>
        <member id="RP.2" qname="lenloc2-resultp:ActivosFinancieros"/>
        <member id="RP.3" qname="lenloc2-resultp:PasivosFinancieros"/>
    </conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-A4ECP.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-anexo4" mainSchemaPrefix="lenloc2-anexo4" name="lenloc2010-A4ECP" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosDimensionDeFilas" inputID="lenloc2-anexo4_Codigo" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo4" nsPrefix="lenloc2-anexo4" outputID="Codigo">
		<member id="lenloc2-anexo4_AvalesEjecutadosClasificacionEconomicaDeGastosFila" qname="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosFila"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosDimensionDeFilas" inputID="lenloc2-anexo4_Descripcion" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo4" nsPrefix="lenloc2-anexo4" outputID="Descripcion">
		<member id="lenloc2-anexo4_AvalesEjecutadosClasificacionEconomicaDeGastosFila" qname="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosFila"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosDimensionDeFilas" inputID="lenloc2-anexo4_ObligacionesReconocidasNetas" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo4" nsPrefix="lenloc2-anexo4" outputID="ObligacionesReconocidasNetas">
		<member id="lenloc2-anexo4_AvalesEjecutadosClasificacionEconomicaDeGastosFila" qname="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosFila"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosDimensionDeFilas" inputID="lenloc2-anexo4_Pagos" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-anexo4" nsPrefix="lenloc2-anexo4" outputID="Pagos">
		<member id="lenloc2-anexo4_AvalesEjecutadosClasificacionEconomicaDeGastosFila" qname="lenloc2-anexo4:AvalesEjecutadosClasificacionEconomicaDeGastosFila"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-INGA.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-econ-ingr-abierta" mainSchemaPrefix="lenloc2-econ-ingr-abierta" name="lenloc2010-INGA" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-abierta_CodigoDeCuenta" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-abierta" nsPrefix="lenloc2-econ-ingr-abierta" outputID="CodigoDeCuenta">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-abierta_Descripcion" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-abierta" nsPrefix="lenloc2-econ-ingr-abierta" outputID="Descripcion">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-importes_PrevisionDefinivaDelEjercicioCorriente" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-importes" nsPrefix="lenloc2-econ-ingr-importes" outputID="PrevisionDefinivaDelEjercicioCorriente">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-importes_DerechosReconocidosDelEjercicioCorriente" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-importes" nsPrefix="lenloc2-econ-ingr-importes" outputID="DerechosReconocidosDelEjercicioCorriente">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-importes_RecaudacionLiquidaDelEjercicioCorriente" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-importes" nsPrefix="lenloc2-econ-ingr-importes" outputID="RecaudacionLiquidaDelEjercicioCorriente">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-econ-ingr-abierta:FilasDimension" inputID="lenloc2-econ-ingr-importes_RecaudacionLiquidaDeEjerciciosCerrados" isTypedDimension="true" ns="http://www.meh.es/taxonomias/lenloc2-econ-ingr-importes" nsPrefix="lenloc2-econ-ingr-importes" outputID="RecaudacionLiquidaDeEjerciciosCerrados">
        <member id="lenloc2-econ-ingr-abierta_FilasTipoDeDimension" qname="lenloc2-econ-ingr-abierta:FilasTipoDeDimension"/>	
    </conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-A1.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-anexo1" mainSchemaPrefix="lenloc2-anexo1" name="lenloc2010-A1" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo1:Conceptosdimension" inputID="lenloc2-anexo1_ObligacionesReconocidas" ns="http://www.meh.es/taxonomias/lenloc2-anexo1" nsPrefix="lenloc2-anexo1" outputID="ObligacionesReconocidas">
		<member id="A1.1" qname="lenloc2-anexo1:InteresesDeDeudaPublica"/>
		<member id="A1.2" qname="lenloc2-anexo1:InteresesDePrestamosYOtrasOperacionesFinancieras"/>
		<member id="A1.3" qname="lenloc2-anexo1:InteresesDeDepositosYFianzas"/>
		<member id="A1.4" qname="lenloc2-anexo1:OtrosIntereses"/>
		<member id="A1.5" qname="lenloc2-anexo1:OperacionesDeIntercambioFinanciero"/>
		<member id="A1.6" qname="lenloc2-anexo1:GastosDeFormalizacionEmisionModificacionYCancelacion"/>
		<member id="A1.7" qname="lenloc2-anexo1:DiferenciasDeCambio"/>
		<member id="A1.8" qname="lenloc2-anexo1:OtrosGastosFinancieros"/>
		<member id="lenloc2-anexo1_Total" qname="lenloc2-anexo1:Total"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-anexo1:Conceptosdimension" inputID="lenloc2-anexo1_InteresesDevengados" ns="http://www.meh.es/taxonomias/lenloc2-anexo1" nsPrefix="lenloc2-anexo1" outputID="InteresesDevengados">
		<member id="A1.1" qname="lenloc2-anexo1:InteresesDeDeudaPublica"/>
		<member id="A1.2" qname="lenloc2-anexo1:InteresesDePrestamosYOtrasOperacionesFinancieras"/>
		<member id="A1.3" qname="lenloc2-anexo1:InteresesDeDepositosYFianzas"/>
		<member id="A1.4" qname="lenloc2-anexo1:OtrosIntereses"/>
		<member id="A1.5" qname="lenloc2-anexo1:OperacionesDeIntercambioFinanciero"/>
		<member id="A1.6" qname="lenloc2-anexo1:GastosDeFormalizacionEmisionModificacionYCancelacion"/>
		<member id="A1.7" qname="lenloc2-anexo1:DiferenciasDeCambio"/>
		<member id="A1.8" qname="lenloc2-anexo1:OtrosGastosFinancieros"/>
		<member id="lenloc2-anexo1_Total" qname="lenloc2-anexo1:Total"/>
	</conceptMap>
</statement>

=== xbrles/lenloc-penloc/resources/ENLOCMaps/lenloc2010-ACR.xml
<?xml version="1.0" encoding="UTF-8"?>
<statement mainSchemaNamespace="http://www.meh.es/taxonomias/lenloc2-onp" mainSchemaPrefix="lenloc2-onp" name="lenloc2010-ACR" xmlns="http://www.inteco.es/xbrl/lenlocpenloc2010/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.inteco.es/xbrl/lenlocpenloc2010/map D:\proyectos\inteco\workspace\inteco_api_xbrl\config\schemas\lenlocpenloc2010-map.xsd">
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:AcreedoresIngresosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_AcreedoresIngresosPendientesAplicacionSaldoRectificaciones" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="AcreedoresIngresosPendientesAplicacionSaldoRectificaciones">
		<!--Todos los member son dimension-domain y no domain-member como deberían ser-->
		<member id="lenloc2-onp-deudores-acreedores_AcreedoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:AcreedoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionIngresos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionIngresos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:AcreedoresIngresosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_AcreedoresIngresosPendientesAplicacionIngresosEfectuados" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="AcreedoresIngresosPendientesAplicacionIngresosEfectuados">
		<!--Todos los member son dimension-domain y no domain-member como deberían ser-->
		<member id="lenloc2-onp-deudores-acreedores_AcreedoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:AcreedoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionIngresos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionIngresos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:AcreedoresIngresosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_AcreedoresIngresosPendientesAplicacionTotalData" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="AcreedoresIngresosPendientesAplicacionTotalData">
		<!--Todos los member son dimension-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_AcreedoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:AcreedoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionIngresos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionIngresos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:AcreedoresIngresosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_AcreedoresIngresosPendientesAplicacionCargosPagos" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="AcreedoresIngresosPendientesAplicacionCargosPagos">
		<!--Todos los member son dimension-domainy no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_AcreedoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:AcreedoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionIngresos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionIngresos"/>
	</conceptMap>
	<conceptMap containerDimensionType="segment" domain="lenloc2-onp:AcreedoresIngresosPendientesAplicacionDimension" inputID="lenloc2-onp-importes_AcreedoresIngresosPendientesAplicacionSaldoPendiente" ns="http://www.meh.es/taxonomias/lenloc2-onp-importes" nsPrefix="lenloc2-onp-importes" outputID="AcreedoresIngresosPendientesAplicacionSaldoPendiente">
		<!--Todos los member son dimension-domain y no domain-member-->
		<member id="lenloc2-onp-deudores-acreedores_AcreedoresNoPresupuestarios" qname="lenloc2-onp-deudores-acreedores:AcreedoresNoPresupuestarios"/>
		<member id="lenloc2-onp-deudores-acreedores_PartidasPendientesAplicacionIngresos" qname="lenloc2-onp-deudores-acreedores:PartidasPendientesAplicacionIngresos"/>
	</conceptMap>
</statement>
