=== xbrles/lenloc-penloc/resources/System/TemplateDictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
<xs:schema elementFormDefault="unqualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="maxOccursType">
		<xs:union memberTypes="xs:nonNegativeInteger">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="unbounded"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:complexType name="RelationshipConstraintType">
		<xs:sequence>
			<xs:element name="Restriction" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="RestrictedAttribute" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="attribute" type="xs:string" use="required"/>
								<xs:attribute name="resolution" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="classificationUri" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="minOccurs" type="xs:nonNegativeInteger" use="optional" default="0"/>
		<xs:attribute name="maxOccurs" type="maxOccursType" use="optional" default="0"/>
		<xs:attribute name="memoClassificationUri" type="xs:anyURI" use="optional" default="memo://ubmatrix.com/Xbrl/Validation/ClassificationEndpoint/#NotSet"/>
		<xs:attribute name="memoCardinalityUri" type="xs:anyURI" use="optional" default="memo://ubmatrix.com/Xbrl/Validation/CardinalityEndpoint/#NotSet"/>
	</xs:complexType>
	<xs:complexType name="DomainTemplateType">
		<xs:sequence>
			<xs:element name="Inheritance" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="classificationUri" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="UponMismatch" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="memoUri" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Behaviors" type="BehaviorsType" minOccurs="0"/>
			<xs:element name="Indices" type="IndicesType" minOccurs="0"/>
			<xs:element name="ReIndexing" type="ReIndexingType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="classificationUri" type="xs:token" use="required"/>
		<xs:attribute name="implementationUri" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="RelationshipTemplateType">
		<xs:complexContent>
			<xs:extension base="DomainTemplateType">
				<xs:sequence>
					<xs:element name="From" type="RelationshipConstraintType" minOccurs="0"/>
					<xs:element name="To" type="RelationshipConstraintType" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="TemplateDictionary">
		<xs:annotation>
			<xs:documentation>Template Dictionary for XBRL domain objects and relationships</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="DomainTemplate" type="DomainTemplateType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RelationshipTemplate" type="RelationshipTemplateType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="BehaviorsType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="QueryBehavior" type="QueryBehaviorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CodeBehavior" type="CodeBehaviorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="XmlBehavior" type="XmlBehaviorType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CodeBehaviorType">
		<xs:complexContent>
			<xs:extension base="BehaviorType">
				<xs:attribute name="implementationURI" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QueryBehaviorType">
		<xs:complexContent>
			<xs:extension base="BehaviorType">
				<xs:attribute name="queryURI" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="XmlBehaviorType">
		<xs:complexContent>
			<xs:extension base="BehaviorType">
				<xs:attribute name="methodURI" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="BehaviorType">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Facilitates reindexing -->
	<xs:complexType name="ReIndexingType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="SelfReIndexer" type="SelfReIndexerType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DescendantReIndexer" type="DescendantReIndexerType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CascadeReIndexer" type="CascadeReIndexerType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CascadeReIndexerType">
		<xs:complexContent>
			<xs:extension base="ReIndexerType">
				<xs:attribute name="relationshipToTarget" type="xs:string" use="optional"/>
				<xs:attribute name="targetHint" type="xs:string" use="optional"/>
				<xs:attribute name="target" type="ReIndexerSourceEnumeration" use="optional"/>
				<xs:attribute name="targetValue" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DescendantReIndexerType">
		<xs:complexContent>
			<xs:extension base="ReIndexerType">
				<xs:attribute name="relationshipToTarget" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SelfReIndexerType">
		<xs:complexContent>
			<xs:extension base="ReIndexerType">
				<xs:sequence>
					<xs:element name="ReClassification" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="hint" type="xs:string" use="required"/>
							<xs:attribute name="classification" type="xs:anyURI" use="optional"/>
							<xs:attribute name="targetHint" type="xs:string" use="optional"/>
							<xs:attribute name="target" type="ReIndexerSourceEnumeration" use="optional"/>
							<xs:attribute name="targetValue" type="xs:string" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ReIndexerType">
		<xs:attribute name="source" type="ReIndexerSourceEnumeration" use="required"/>
		<xs:attribute name="force" type="xs:string" use="optional"/>
		<xs:attribute name="sourceHint" type="xs:string" use="optional"/>
		<xs:attribute name="order" type="xs:integer" use="optional" default="1000000"/>
	</xs:complexType>
	<xs:simpleType name="ReIndexerSourceEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Undefined"/>
			<xs:enumeration value="Attribute"/>
			<xs:enumeration value="LocalName"/>
			<xs:enumeration value="Value"/>
			<xs:enumeration value="Namespace"/>
			<xs:enumeration value="SubstitutionGroup"/>
			<xs:enumeration value="PrimaryPrefix"/>
			<xs:enumeration value="PhysicalUri"/>
			<xs:enumeration value="RelatedPhysicalUri"/>
			<xs:enumeration value="Add"/>
			<xs:enumeration value="Remove"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Added to facilitate dynamic indexing -->
	<xs:complexType name="IndicesType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="FullNameIndex" type="FullNameIndexType" minOccurs="0"/>
				<xs:element name="LocalNameIndex" type="LocalNameIndexType" minOccurs="0"/>
				<xs:element name="NodeValueIndex" type="NodeValueIndexType" minOccurs="0"/>
				<xs:element name="AttributeIndex" type="AttributeIndexType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttributeIndexType">
		<xs:complexContent>
			<xs:extension base="IndexType">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="FullNameIndexType">
		<xs:complexContent>
			<xs:extension base="IndexType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LocalNameIndexType">
		<xs:complexContent>
			<xs:extension base="IndexType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NodeValueIndexType">
		<xs:complexContent>
			<xs:extension base="IndexType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="IndexType"/>
</xs:schema>

=== xbrles/lenloc-penloc/resources/System/Xbrl21Templates.xml
<?xml version="1.0"?>
<TemplateDictionary
    name="XBRL 2.1 Templates"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ubmfi="http://www.ubmatrix.com/2005/function/instance"
   xmlns:ubmft="http://www.ubmatrix.com/2005/function/taxonomy"
   xmlns:xbrli ="http://www.xbrl.org/2003/instance"
   xmlns:ubmfdts="http://www.ubmatrix.com/2005/function/dts"
   xmlns:ubmfedit="http://www.ubmatrix.com/2005/function/edit"
   xmlns:psvi="http://www.ubmatrix.com/2005/function/psvi"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xsi:noNamespaceSchemaLocation="TemplateDictionary.xsd">

    <!-- Please don't use this, and don't create an implementation!
         The goal here is to provide "root" level methods -->
    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl#AbstractXbrlDomain"
        implementationUri="[AbstractXbrlDomain]">
        <Behaviors>
            <XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl#AbstractXbrlDomain.SetValue"
                         name="SetValue" />
            <XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl#AbstractXbrlDomain.SetAttributeValue"
                         name="SetAttributeValue" />
            <XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl#AbstractXbrlDomain.AddVONamespaceDeclaration"
                         name="AddVONamespaceDeclaration" />
            <XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl#AbstractXbrlDomain.RemoveVONamespaceDeclaration"
                         name="RemoveVONamespaceDeclaration" />
            <XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl#AbstractXbrlDomain.GetDTSNode"
                         name="GetDTSNode" />
            <CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#AbstractXbrlDomain"
                          name="addNamespaceDeclaration" />
            <CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#AbstractXbrlDomain"
                          name="removeNamespaceDeclaration" />
            <CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#AbstractXbrlDomain"
                          name="removeAllNamespaceDeclarations" />
        </Behaviors>
    </DomainTemplate>

    <!-- DTS specific objects -->
    <RelationshipTemplate
        classificationUri="relationship://ubmatrix.com/Xbrl/DTSGraph#DtsEntryRelationship"
        implementationUri="implementation://ubmatrix.com/Xbrl#SimpleRelationship">
        <!-- Inheritance classificationUri="relationship://ubmatrix.com/Xbrl#BaseRelationship" / -->
    </RelationshipTemplate>

    <RelationshipTemplate
        classificationUri="relationship://ubmatrix.com/Xbrl/DTSGraph#DtsEdge"
        implementationUri="implementation://ubmatrix.com/Xbrl#SimpleRelationship">
        <!-- Inheritance classificationUri="relationship://ubmatrix.com/Xbrl#BaseRelationship" / -->
    </RelationshipTemplate>
    
    <!-- Taxonomy objects -->

    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl#UnclassifiedElement"
        implementationUri="implementation://ubmatrix.com/Xbrl#SchemaDomain">
		<Indices>
			<FullNameIndex />
		</Indices>
		<ReIndexing>
			<SelfReIndexer  source="LocalName" order="0"/>		
			<SelfReIndexer source="Attribute" sourceHint="name" order="0" />		
			<CascadeReIndexer source="Attribute" sourceHint="name" relationshipToTarget="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#DefinedBySubstitutionGroup'/'*'" target="Attribute" targetHint="substitutionGroup" targetValue="concat(ubmft:prefix(ubmft:substitution-group-node(.)),':','{0}')"  order="1"/>					
		</ReIndexing>
	</DomainTemplate>

    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl/Namespace#Namespace"
        implementationUri="implementation://ubmatrix.com/Xbrl/Namespace#Namespace">
		<Indices>
			<NodeValueIndex />
		</Indices>
		<ReIndexing>
			<SelfReIndexer source="LocalName" />
			<SelfReIndexer source="Value" />
			<DescendantReIndexer  source="Value" force="Namespace"/>	
		</ReIndexing>	
    </DomainTemplate>

    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl/Namespace#NamespacePrefix"
        implementationUri="implementation://ubmatrix.com/Xbrl/Namespace#NamespacePrefix">
		<Indices>
			<LocalNameIndex />
		</Indices>
		<ReIndexing>
			<SelfReIndexer source="LocalName" />
			<SelfReIndexer source="Value" />
			<DescendantReIndexer  source="Value" force="Namespace"/>	
		</ReIndexing>		
    </DomainTemplate>

    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl/Taxonomy#Taxonomy"
        implementationUri="implementation://ubmatrix.com/Xbrl#SchemaDomain">

        <Behaviors>
			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"
                          name="createInstance" />
			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="createConcept" />	
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="extendTaxonomy" />	
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="setTargetNamespaceIdentifier" />	
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="addLinkbaseRef" />	
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"
					  	  name="removeLinkbaseRef" />
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"
					  	  name="removeSchemaRef" />
  			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"
					  	  name="removeTargetNamespaceIdentifier" />
			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="createLinkbase" />	
			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="createRole" />	
			<CodeBehavior implementationURI="behavior://ubmatrix.com/Xbrl/Behavior#TaxonomyFile"	
						  name="createArcRole" />	
			<XmlBehavior methodURI="behavior://ubmatrix.com/Xbrl/Taxonomy#Taxonomy.RemoveConcept"
						 name="removeConcept" />						 
        </Behaviors>
		<Indices>
			<FullNameIndex />
		</Indices>
		<ReIndexing>
			<SelfReIndexer  source="LocalName" order="0"/>
			<SelfReIndexer  source="PhysicalUri" order="0"/>
			<SelfReIndexer source="Attribute" sourceHint="targetNamespace" order="0"/>
			<CascadeReIndexer source="RelatedPhysicalUri"  
				relationshipToTarget="." 
				target="Attribute" 
				targetHint="xsi:schemaLocation" 
				targetValue="ubmfedit:schema-location(.)"
				order="1"/>			
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/+'relationship://ubmatrix.com/Xbrl/Relationship#TaxonomyReferencesLinkbase'/'*'" 
				target="RelatedPhysicalUri" 
				order="1"/>		
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#TaxonomyReferencesTaxonomy'/'*'" 
				target="RelatedPhysicalUri" 
				order="1"/>	
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#InstanceReferencesTaxonomy'/'*'"
				target="RelatedPhysicalUri" 
				order="1"/>
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#TaxonomyReferencesTaxonomy'" 
				target="RelatedPhysicalUri" 
				order="1"/>	
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#TaxonomyReferencesLinkbase'" 
				target="RelatedPhysicalUri" 
				order="1"/>	
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#InstanceReferencesTaxonomy'"
				target="RelatedPhysicalUri" 
				order="1"/>				
			<CascadeReIndexer source="PrimaryPrefix" relationshipToTarget="." target="Attribute"  targetHint="targetNamespace" order="1"/>			 <CascadeReIndexer source="Attribute" sourceHint="targetNamespace" relationshipToTarget="." target="PrimaryPrefix"  order="1"/>
			<CascadeReIndexer source="PrimaryPrefix" relationshipToTarget="/-'relationship://ubmatrix.com/Xbrl/Relationship#InstanceReferencesTaxonomy'/'*'" target="PrimaryPrefix"  force="Namespace" order="1"/>
			<DescendantReIndexer source="Attribute"  force="Namespace" sourceHint="targetNamespace xmlns:*" order="3"/>
		</ReIndexing>		
	</DomainTemplate>

    <!-- Added Locator -->
    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl/Linkbase#Locator"
        implementationUri="implementation://ubmatrix.com/Xbrl#InstanceDomain">
        <Indices>
        	<AttributeIndex name="http://www.w3.org/1999/xlink#label" />           	
        </Indices>
		<ReIndexing>
			<SelfReIndexer  source="LocalName" />
			<SelfReIndexer source="Attribute" sourceHint="xlink:label xlink:href" />
			<CascadeReIndexer  source="Attribute" sourceHint="xlink:label" 
				relationshipToTarget="/+'relationship://ubmatrix.com/Xbrl/Relationship#LocatorLocatesResource'/'*'  /+'relationship://ubmatrix.com/Xbrl/Relationship#LocatorLocatesDomainObject'/'*'" 
			    target="Attribute" targetHint="xlink:from xlink:to xlink:label"/>
  		<CascadeReIndexer source="PhysicalUri"  
				relationshipToTarget="." 
				target="Attribute" 
				targetHint="xlink:href" 
				targetValue="ubmfedit:reference(.,'domain://ubmatrix.com/Xbrl/Linkbase#Locator')"
				order="1"/>		    
		</ReIndexing>		        
    </DomainTemplate>

    <!-- Added ReferencePart -->
    <DomainTemplate
        classificationUri="domain://ubmatrix.com/Xbrl/Taxonomy#LocalReferencePart"
        implementationUri="implementation://ubmatrix.com/Xbrl#SchemaDomain">
